name: Fetch Stock Data

on:
  schedule:
    - cron: "0 1 * * 1-5"   # 每天台灣上午9點跑 (UTC+0 加8hr)
  workflow_dispatch:         # 手動觸發

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |    
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch_stock_data
        run: python fetch_stock_data.py

      - name: Ensure data folder exists
        run: mkdir -p data

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv || echo "No CSV files to add"
          git commit -m "Update stock data [skip ci]" || echo "No changes to commit"
          git push
